services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=e5XwNS6jEa52zk1Ah
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"

volumes:
  postgres: